spring:
  datasource:
    url: 'jdbc:h2:file:./db/h2'
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  hibernate:
    show_sql: true

telegram:
  api:
    url: 'https://api.telegram.org/'
  bot:
    id: '1175490708:AAHTrfqu5fyn6o6tDUoiPu2MwFg4raHY2EY'
    #'1104514641:AAHgsNR4J4A9P0CZIo_dNn-nZWAevDMhWo4'
  channel:
    id: '468654555'
    #'-435910891'
